
// This file has been generated by the GUI designer. Do not modify.
namespace KaleidoscopeGenerator.UI.Gtk
{
	public partial class MainWindow
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.SpinButton _geometryWidthSpinButton;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.ComboBox _typeComboBox;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Button _imageSelectButton;
		
		private global::Gtk.Image _previewImage;
		
		private global::Gtk.DrawingArea _drawingArea;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget KaleidoscopeGenerator.UI.Gtk.MainWindow
			this.Name = "KaleidoscopeGenerator.UI.Gtk.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child KaleidoscopeGenerator.UI.Gtk.MainWindow.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 16;
			this.vbox1.BorderWidth = ((uint)(11));
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Mirrow width");
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this._geometryWidthSpinButton = new global::Gtk.SpinButton (10, 500, 1);
			this._geometryWidthSpinButton.CanFocus = true;
			this._geometryWidthSpinButton.Name = "_geometryWidthSpinButton";
			this._geometryWidthSpinButton.Adjustment.PageIncrement = 10;
			this._geometryWidthSpinButton.ClimbRate = 1;
			this._geometryWidthSpinButton.Numeric = true;
			this._geometryWidthSpinButton.Value = 100;
			this.vbox1.Add (this._geometryWidthSpinButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this._geometryWidthSpinButton]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of Mirrors");
			this.vbox1.Add (this.label2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label2]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this._typeComboBox = global::Gtk.ComboBox.NewText ();
			this._typeComboBox.Name = "_typeComboBox";
			this.vbox1.Add (this._typeComboBox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this._typeComboBox]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Base image");
			this.vbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label3]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this._imageSelectButton = new global::Gtk.Button ();
			this._imageSelectButton.CanFocus = true;
			this._imageSelectButton.Name = "_imageSelectButton";
			this._imageSelectButton.UseUnderline = true;
			this._imageSelectButton.Label = global::Mono.Unix.Catalog.GetString ("Select");
			this.vbox1.Add (this._imageSelectButton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this._imageSelectButton]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this._previewImage = new global::Gtk.Image ();
			this._previewImage.WidthRequest = 100;
			this._previewImage.Name = "_previewImage";
			this.vbox1.Add (this._previewImage);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this._previewImage]));
			w7.Position = 6;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this._drawingArea = new global::Gtk.DrawingArea ();
			this._drawingArea.Name = "_drawingArea";
			this.hbox1.Add (this._drawingArea);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._drawingArea]));
			w9.Position = 1;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 792;
			this.DefaultHeight = 543;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
